thisdir = class/System.Activities.DurableInstancing
SUBDIRS = 
include ../../build/rules.make

LIBRARY = System.Activities.DurableInstancing.dll
LIB_REFS = System System.Core
LIB_MCS_FLAGS =

TEST_MCS_FLAGS = $(LIB_MCS_FLAGS)

EXTRA_DISTFILES =

include ../../build/library.make
